### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by SidneyMachara** [Developers-Circle-Gaborone/bwjobsforgraduates#10]
Make it Beautiful  ( with social links, facebook , twiter , instagram)

**Comment by Segolana** [comment]
Attempt this 1

**Comment by Tumo505** [comment]
i'd like to start working on the footer

**Comment by JinxTL** [comment]
hi guys. i'm going to try this too

**Comment by Gaone1996** [comment]
working on it

**Comment by SidneyMachara** [comment]
who is working on this. when someone request to work on something please dont also make same request while you see its taken
