### ISSUE TITLE
Style navbar

### ISSUE THREAD

**Issue by Modise50** [Developers-Circle-Gaborone/bwjobsforgraduates#24]

**Comment by thenewpyjiang** [comment]
Hi there! I would like to attempt on this issue, can you assign me the task? Thank you!

**Comment by thenewpyjiang** [comment]
Hi! I made a pull request, please do review it! :) [PR#56](https://github.com/Developers-Circle-Gaborone/bwjobsforgraduates/pull/56)

**Comment by RamanaVem** [comment]
is it done?
