### ISSUE TITLE
create src folder

### ISSUE THREAD

**Issue by Modise50** [Developers-Circle-Gaborone/bwjobsforgraduates#36]
![profile_pic](https://user-images.githubusercontent.com/37755668/67146165-84437c00-f288-11e9-8a10-1d199641332c.jpg)
![header](https://user-images.githubusercontent.com/37755668/67146166-84437c00-f288-11e9-826d-2bc68c69f97c.jpg)

lease create a folder to save/upload the logo and header images and such

**Comment by naekkeoya** [comment]
I can do this one!

**Comment by skittu** [comment]
#71

**Comment by skittu** [comment]
hey, i have solved the issue please check it out #71
