### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by SidneyMachara** [Developers-Circle-Gaborone/bwjobsforgraduates#9]
Create a good looking navbar (pleeeease).

**Comment by BPhumusa** [comment]
for the navbar do we create both html code with css?

**Comment by samKenpachi011** [comment]
Hi guys i would like to start my contribution by working on the nav bar.@BPhumusa can we use vanilla js?

**Comment by BPhumusa** [comment]
@samKenpachi011  vanilla js?

**Comment by SidneyMachara** [comment]
> for the navbar do we create both html code with css?

yes you create both

**Comment by Richardmckid** [comment]
Vanilla JS is pure JavaScript not a framework

**Comment by BOGA-518** [comment]
First contribution Navbar

**Comment by Johndisang** [comment]
working on it

**Comment by vikasprashar99** [comment]
added a simple side navbar

**Comment by JinxTL** [comment]
created a simple navigation bar. someone who masters css help make it super.
